print("************************************************" )
print("hola mundo" )
print("Practica de repositorio" )
print("testeo de repositorio" )
print("************************************************" )
print("Practica de push en git")